<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

if ( ! function_exists('read')) {
	function read($file)
	{
		$CI =& get_instance();
        $CI->load->library('excel');
		 
		// read file from path
		$objPHPExcel = PHPExcel_IOFactory::load($file);
		 
		// get only the Cell Collection
		$cell_collection = $objPHPExcel->getActiveSheet()->getCellCollection();
		 
		// extract to a PHP readable array format
		foreach ($cell_collection as $cell) {
		    $column = $objPHPExcel->getActiveSheet()->getCell($cell)->getColumn();
		    $row = $objPHPExcel->getActiveSheet()->getCell($cell)->getRow();
		    $data_value = $objPHPExcel->getActiveSheet()->getCell($cell)->getValue();
		 
		    // header will/should be in row 1 only. of course this can be modified to suit your need.
		    if ($row == 1) {
		        $header[$row][$columns] = $data_value;
		    } else {
		        $arr_data[$row][$col] = $data_value;
		    }
		}
		 
		//send the data in an array format
		$data['header'] = $header;
		$data['values'] = $arr_data;

		return $data;
	}
}

if ( ! function_exists('create')) {
	function create()
	{
		$CI =& get_instance();
        $CI->load->library('excel');

		// Create new PHPExcel object
		$objPHPExcel = new PHPExcel();
	
		// Set document properties
		$objPHPExcel->getProperties()->setCreator("mojito.com")
									 ->setLastModifiedBy("mojito.com")
									 ->setTitle("Office 2007 XLSX Test Document")
									 ->setSubject("Office 2007 XLSX Test Document")
									 ->setDescription("Test document for Office 2007 XLSX, generated by PHP classes.")
									 ->setKeywords("office 2007 openxml php")
									 ->setCategory("Test result file");
		
		// Add some data
		$objPHPExcel->setActiveSheetIndex(0)
		            ->setCellValue('A1', 'Hello')
		            ->setCellValue('B2', 'world!')
		            ->setCellValue('C1', 'bonjour')
		            ->setCellValue('C2', 'monde')
		            ->setCellValue('A4', 'tutorial from: mojito.com');
		 
		// Rename worksheet (worksheet, not filename)
		$objPHPExcel->getActiveSheet()->setTitle('createdUsingPHPExcel');
		 
		// Set active sheet index to the first sheet, so Excel opens this as the first sheet
		$objPHPExcel->setActiveSheetIndex(0);
		 
		// Redirect output to a client’s web browser (Excel2007)
		//clean the output buffer
		ob_end_clean();

		// this is the header given from PHPExcel examples. but the output seems somewhat corrupted in some cases.
		// header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
		// header('Content-type: application/vnd.ms-excel');
		// so, we use this header instead.
		// 2007 xlsx
		// header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
		// 2003 xls
		header('Content-type: application/vnd.ms-excel');
		header('Content-Disposition: attachment;filename="excel.xls"');
		header('Cache-Control: max-age=0');
		
		// Save it as an excel 2003 file use 'Excel5'
		// Save it as an excel 2007 file use 'Excel2007'
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objWriter->save("excel.xls");
	}
}

if ( ! function_exists('to_excel')) {
	function to_excel($array, $filename)
	{
        header('Content-type: application/vnd.ms-excel');
        header('Content-Disposition: attachment; filename='.$filename.'.xls');

		// Filter all keys, they'll be table headers
        $h = array();
        foreach ($array as $key => $val) {
            if ( ! in_array($key, $h)) {
				$h[] = $key;
            }
        }
        
        //echo the entire table headers
        echo '<table><tr>';
        foreach ($h as $key) {
            $key = ucwords($key);
            echo '<th>' . $key . '</th>';
        }
        echo '</tr>';
        
        foreach ($array as $row) {
			echo '<tr>';
            foreach ($row as $val) {
                 writeRow($val);   
            }
        }

        echo '</tr>';
        echo '</table>';
	}
}

if ( ! function_exists('writeRow')) {
    function writeRow($val) {
        echo '<td>'.utf8_decode($val).'</td>';              
    }
}

/* Location: application/helpers/phpexcel_helper.php */
